global using AutoMapper;
global using Microsoft.EntityFrameworkCore;
global using SMS.Core.IServices;
global using SMS.Infrastructure.Bases;
global using SMS.Models.Entities;
global using SMS.Models.Helpers;
global using SMS.Models.Results;
global using SMS.Persistance.IRepos;
global using SMS.VModels.DTOS;
