global using AutoMapper;
global using Core.IServices;
global using Infrastructure.Bases;
global using Microsoft.EntityFrameworkCore;
global using Models.Entities;
global using Models.Helpers;
global using Models.Results;
global using Persistance.IRepos;
global using VModels.DTOS;
